# Generated by Django 5.0.6 on 2024-05-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_code', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=256)),
                ('uuid_project', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
