# Generated by Django 5.0.1 on 2024-01-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0012_alter_tabela_fluxo_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelatemporaria',
            name='parcelas',
            field=models.CharField(max_length=50),
        ),
    ]
