# Generated by Django 5.0.3 on 2024-04-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0031_rename_tabela_fluxo_cashflowentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflowentry',
            old_name='vencimento',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='tabelatemporaria',
            old_name='vencimento',
            new_name='due_date',
        ),
    ]
