# Generated by Django 5.0.3 on 2024-04-04 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0033_rename_descricao_cashflowentry_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflowentry',
            old_name='observacao',
            new_name='observation',
        ),
        migrations.RenameField(
            model_name='tabelatemporaria',
            old_name='observacao',
            new_name='observation',
        ),
    ]
