# Generated by Django 5.0.3 on 2024-04-04 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0035_rename_valor_cashflowentry_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflowentry',
            old_name='conta_contabil',
            new_name='general_ledger_account',
        ),
        migrations.RenameField(
            model_name='tabelatemporaria',
            old_name='conta_contabil',
            new_name='general_ledger_account',
        ),
    ]
