# Generated by Django 5.0.3 on 2024-04-04 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0036_rename_conta_contabil_cashflowentry_general_ledger_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflowentry',
            old_name='uuid_conta_contabil',
            new_name='uuid_general_ledger_account',
        ),
        migrations.RenameField(
            model_name='tabelatemporaria',
            old_name='uuid_conta_contabil',
            new_name='uuid_general_ledger_account',
        ),
    ]
