# Generated by Django 5.0.3 on 2024-04-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0039_rename_parcelas_total_cashflowentry_total_installments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflowentry',
            old_name='natureza',
            new_name='transaction_type',
        ),
        migrations.RenameField(
            model_name='tabelatemporaria',
            old_name='natureza',
            new_name='transaction_type',
        ),
    ]
