# Generated by Django 5.0.3 on 2024-04-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0040_rename_natureza_cashflowentry_transaction_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflowentry',
            old_name='data_criacao',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='tabelatemporaria',
            old_name='data_criacao',
            new_name='creation_date',
        ),
    ]
