# Generated by Django 5.0.3 on 2024-04-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0042_rename_uuid_correlacao_cashflowentry_uuid_correlation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Totais_mes_fluxo',
            new_name='Months_list_cash_flow',
        ),
    ]
