# Generated by Django 5.0.3 on 2024-04-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0043_rename_totais_mes_fluxo_months_list_cash_flow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='months_list_cash_flow',
            old_name='inicio_mes',
            new_name='start_of_month',
        ),
    ]
