# Generated by Django 5.0.3 on 2024-04-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0045_rename_fim_mes_months_list_cash_flow_end_of_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='months_list_cash_flow',
            old_name='data_formatada',
            new_name='formatted_date',
        ),
    ]
