# Generated by Django 5.0.3 on 2024-04-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0046_rename_data_formatada_months_list_cash_flow_formatted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='months_list_cash_flow',
            old_name='saldo_mensal',
            new_name='monthly_balance',
        ),
        migrations.RenameField(
            model_name='months_list_cash_flow',
            old_name='total_credito',
            new_name='total_credit',
        ),
        migrations.RenameField(
            model_name='months_list_cash_flow',
            old_name='total_debito',
            new_name='total_debit',
        ),
    ]
