# Generated by Django 5.0.3 on 2024-04-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0047_rename_saldo_mensal_months_list_cash_flow_monthly_balance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TabelaTemporaria',
            new_name='TemporaryTable',
        ),
    ]
