# Generated by Django 5.0.3 on 2024-04-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0052_rename_agencia_banks_bank_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banks',
            old_name='conta',
            new_name='bank_account',
        ),
    ]
