# Generated by Django 5.0.3 on 2024-04-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0053_rename_conta_banks_bank_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banks',
            old_name='saldo_inicial',
            new_name='initial_balance',
        ),
    ]
