# Generated by Django 5.0.3 on 2024-04-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0057_rename_uuid_departamento_departments_uuid_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banks',
            old_name='status',
            new_name='bank_status',
        ),
    ]
