# Generated by Django 5.0.3 on 2024-04-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0058_rename_status_banks_bank_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=256)),
                ('uuid_document_type', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
