# Generated by Django 5.0.3 on 2024-04-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0059_documenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowentry',
            name='document_type',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='periods',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='uuid_document_type',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
