# Generated by Django 5.0.3 on 2024-04-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0060_cashflowentry_document_type_cashflowentry_periods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowentry',
            name='notes',
            field=models.CharField(default='none', max_length=256),
            preserve_default=False,
        ),
    ]
