# Generated by Django 5.0.6 on 2024-05-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0062_cashflowentry_weekend_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowentry',
            name='department',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='uuid_department',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarytable',
            name='department',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporarytable',
            name='document_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporarytable',
            name='notes',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporarytable',
            name='periods',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporarytable',
            name='uuid_correlation',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarytable',
            name='uuid_department',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarytable',
            name='uuid_document_type',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarytable',
            name='weekend_action',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
