# Generated by Django 5.0.6 on 2024-05-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0063_cashflowentry_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowentry',
            name='department',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='cashflowentry',
            name='uuid_department',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
