# Generated by Django 5.0.6 on 2024-05-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0065_cashflowentry_department_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowentry',
            name='department',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowentry',
            name='department_percentage',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowentry',
            name='document_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowentry',
            name='uuid_general_ledger_account',
            field=models.UUIDField(blank=True),
        ),
    ]
