# Generated by Django 5.0.6 on 2024-05-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0066_alter_cashflowentry_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowentry',
            name='uuid_installments_correlation',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
