# Generated by Django 5.0.6 on 2024-05-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0067_cashflowentry_uuid_installments_correlation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowentry',
            name='uuid_transference',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
