# Generated by Django 5.0.6 on 2024-05-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0068_cashflowentry_uuid_transference'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowentry',
            name='uuid_partial_settlement_correlation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
