# Generated by Django 5.0.6 on 2024-05-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0069_cashflowentry_uuid_partial_settlement_correlation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowentry',
            name='uuid_partial_settlement_correlation',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
