# Generated by Django 5.0.6 on 2024-05-19 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0070_alter_cashflowentry_uuid_partial_settlement_correlation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflowentry',
            name='uuid_correlation',
        ),
        migrations.RemoveField(
            model_name='temporarytable',
            name='uuid_correlation',
        ),
    ]
