# Generated by Django 5.0.6 on 2024-05-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0071_remove_cashflowentry_uuid_correlation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowentry',
            name='project',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='uuid_project',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
