# Generated by Django 5.0.6 on 2024-05-30 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0074_rename_name_inventory_item_inventory_uuid_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='item',
            new_name='inventory_item',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='inventory_quantity',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='uuid_item',
            new_name='uuid_inventory_item',
        ),
    ]
