# Generated by Django 5.0.6 on 2024-05-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0075_rename_item_inventory_inventory_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_item_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
