# Generated by Django 5.0.6 on 2024-06-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0076_inventory_inventory_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowentry',
            name='inventory_item',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='inventory_item_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='inventory_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='uuid_inventory_item',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
