# Generated by Django 5.0.6 on 2024-06-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0077_cashflowentry_inventory_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowentry',
            name='inventory_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
