# Generated by Django 5.0.6 on 2024-06-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0078_alter_cashflowentry_inventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowentry',
            name='inventory_item',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowentry',
            name='inventory_item_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
