# Generated by Django 5.0.6 on 2024-06-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0079_alter_cashflowentry_inventory_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_quantity_cash_flow',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
