# Generated by Django 5.0.6 on 2024-06-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0080_inventory_inventory_quantity_cash_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ssn_tax_id', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('ein_tax_id', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('alias_name', models.CharField(blank=True, max_length=20, null=True)),
                ('area_code', models.CharField(blank=True, max_length=3, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('street_number', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=10, null=True)),
                ('checking_account', models.CharField(blank=True, max_length=20, null=True)),
                ('account_holder_tax_id', models.CharField(blank=True, max_length=20, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
