# Generated by Django 5.0.6 on 2024-06-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0081_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='entities',
            name='uuid_entities_item',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
