# Generated by Django 5.0.6 on 2024-06-15 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0082_entities_uuid_entities_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entities',
            old_name='uuid_entities_item',
            new_name='uuid_entities',
        ),
    ]
