# Generated by Django 5.0.6 on 2024-06-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0084_cashflowentry_entity_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowentry',
            name='entity_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
