# Generated by Django 5.0.3 on 2024-04-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthsListSettled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_month', models.DateField(blank=True, null=True)),
                ('end_of_month', models.DateField(blank=True, null=True)),
                ('formatted_date', models.CharField(max_length=255, unique=True)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('monthly_balance', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='SettledEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_flow_id', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('observation', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('general_ledger_account', models.CharField(max_length=100)),
                ('current_installment', models.IntegerField()),
                ('total_installments', models.IntegerField()),
                ('tags', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=50)),
                ('original_creation_date', models.DateTimeField(blank=True, null=True)),
                ('settlement_date', models.DateTimeField()),
                ('settlement_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('settlement_bank_id', models.IntegerField(blank=True, null=True)),
                ('uuid_correlation', models.UUIDField(blank=True, null=True)),
                ('uuid_correlation_installments', models.UUIDField(blank=True, null=True)),
                ('uuid_general_ledger_account', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
