# Generated by Django 5.0.6 on 2024-05-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settled_entry', '0003_rename_uuid_correlation_installments_settledentry_uuid_partial_settlement_correlation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settledentry',
            old_name='uuid_partial_settlement_correlation',
            new_name='uuid_partial_settlement_correlatio',
        ),
    ]
