# Generated by Django 5.0.6 on 2024-05-19 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settled_entry', '0005_rename_uuid_partial_settlement_correlatio_settledentry_uuid_partial_settlement_correlation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settledentry',
            name='uuid_correlation',
        ),
    ]
