# Generated by Django 5.0.6 on 2024-06-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settled_entry', '0006_remove_settledentry_uuid_correlation'),
    ]

    operations = [
        migrations.AddField(
            model_name='settledentry',
            name='department',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settledentry',
            name='department_percentage',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settledentry',
            name='document_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settledentry',
            name='notes',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settledentry',
            name='periods',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settledentry',
            name='project',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settledentry',
            name='uuid_department',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settledentry',
            name='uuid_document_type',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settledentry',
            name='uuid_installments_correlation',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settledentry',
            name='uuid_project',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settledentry',
            name='weekend_action',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
