# Generated by Django 5.0.6 on 2024-06-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settled_entry', '0007_settledentry_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settledentry',
            name='inventory_item',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settledentry',
            name='inventory_item_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settledentry',
            name='inventory_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='settledentry',
            name='uuid_inventory_item',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
