# Generated by Django 5.0.6 on 2024-06-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settled_entry', '0008_settledentry_inventory_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settledentry',
            name='entity_full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settledentry',
            name='entity_tax_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settledentry',
            name='uuid_entity',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
