# Generated by Django 5.0.6 on 2024-06-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settled_entry', '0009_settledentry_entity_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settledentry',
            name='entity_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
