# Generated by Django 5.0.3 on 2024-03-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceldocument',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='exceldocument',
            name='json_data',
            field=models.JSONField(default=dict),
        ),
    ]
