# Generated by Django 5.0.3 on 2024-03-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0002_remove_exceldocument_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldocument',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
