# Generated by Django 5.0.3 on 2024-03-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0003_alter_exceldocument_json_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_a', models.CharField(blank=True, max_length=200, null=True)),
                ('column_b', models.CharField(blank=True, max_length=200, null=True)),
                ('column_c', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
