# Generated by Django 5.0.3 on 2024-03-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0004_exceldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='column_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='column_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='column_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
