# Generated by Django 5.0.3 on 2024-03-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0005_alter_exceldata_column_a_alter_exceldata_column_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=255)),
                ('column2', models.CharField(max_length=255)),
                ('column3', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ExcelData',
        ),
        migrations.DeleteModel(
            name='ExcelDocument',
        ),
    ]
