# Generated by Django 5.0.3 on 2024-03-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0007_rename_account_chart_of_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart_of_accounts',
            name='column4',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
