# Generated by Django 5.0.3 on 2024-03-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0009_remove_chart_of_accounts_column1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart_of_accounts',
            name='column1',
            field=models.CharField(choices=[('Crédito', 'Crédito'), ('Débito', 'Débito')], default='null', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
