# Generated by Django 5.0.3 on 2024-03-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0010_chart_of_accounts_column1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart_of_accounts',
            name='column2',
            field=models.CharField(choices=[('Receitas Operacionais', 'Receitas Operacionais'), ('Receitas Não Operacionais', 'Receitas Não Operacionais'), ('Despesas Operacionais', 'Despesas Operacionais'), ('Despesas Não Operacionais', 'Despesas Não Operacionais'), ('Transferência entre Contas', 'Transferência entre Contas')], max_length=255),
        ),
    ]
