# Generated by Django 5.0.3 on 2024-03-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0011_alter_chart_of_accounts_column2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart_of_accounts',
            old_name='column4',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='chart_of_accounts',
            old_name='column2',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='chart_of_accounts',
            old_name='column1',
            new_name='nature',
        ),
        migrations.RenameField(
            model_name='chart_of_accounts',
            old_name='column3',
            new_name='subgroup',
        ),
    ]
