# Generated by Django 5.0.3 on 2024-03-20 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0012_rename_column4_chart_of_accounts_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart_of_accounts',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
