# Generated by Django 5.0.3 on 2024-03-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0013_chart_of_accounts_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart_of_accounts',
            name='group',
            field=models.CharField(choices=[('Receitas Operacionais', 'Receitas Operacionais'), ('Receitas Não Operacionais', 'Receitas Não Operacionais'), ('Despesas Operacionais', 'Despesas Operacionais'), ('Despesas Não Operacionais', 'Despesas Não Operacionais')], max_length=255),
        ),
    ]
