# Generated by Django 5.0.3 on 2024-03-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0014_alter_chart_of_accounts_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounts_list', models.CharField(max_length=255)),
                ('uuid_accounts_list', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Groups_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups_list', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subgroups_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroups_list', models.CharField(max_length=255)),
            ],
        ),
    ]
